name: Run

on:
  push:
    branches:
      - "main"
    paths:
      - "scripts/**"
      - "**.zig"

jobs:
  run_all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Run all
        run: bash ./scripts/run.sh all
